---
title: "Hofmann Lab Code"
author: "Zoe Fung"
date: "10/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install/load packages
library(tidyverse)
library(readxl)
library(readr)
library(janitor)
library(here)
library(lubridate)
```

### Importing data
```{r}
trisdata <- read_csv(here("data","7.12.2021-tris.csv")) %>%
  filter(row_number()!=c(1:5)) %>% # remove the first 5 rows
  row_to_names(row_number=1) %>% # make the top row the column headers
  clean_names() %>% # clean up column header names
  mutate(date_lubridate=mdy(date)) %>% # tell R "date" is a DATE
  mutate(time_lubridate=hms(time)) %>% # tell R "time" is a TIME
  unite(date_time, c(date, time), sep = " ", remove = TRUE) %>% # combine the date and time columns
  mutate(date_time_lubridate=mdy_hms(date_time)) # tell R "date_time" is a DATE and a TIME
```

### Creating the OMEGAS temperature table
```{r}
omegas <- data.frame(trisdata$voltage_1_m_v,trisdata$voltage_2_m_v,trisdata$voltage_3_m_v,trisdata$voltage_4_m_v) %>% # create OMEGAS data frame with the tris voltages
  mutate(mv1=as.numeric(trisdata.voltage_1_m_v),
         mv2=as.numeric(trisdata.voltage_2_m_v),
         mv3=as.numeric(trisdata.voltage_3_m_v),
         mv4=as.numeric(trisdata.voltage_4_m_v)) %>% # changing data to numeric arguments
  select(mv1, mv2, mv3, mv4) # cleaning data frame
```

### Calculating Rthermistor
```{r}
omegas_v <- omegas %>% # create new dataframe using omegas values
  mutate(v1=(mv1/1000),
         v2=(mv2/1000),
         v3=(mv3/1000),
         v4=(mv4/1000)) %>% # converting the mV to volts
  mutate(vbattery=((v2/100)*101.57)) %>% # calculate vbattery
  mutate(z=(v4/100)+vbattery*(15000/(1000000+15000))) %>% # calculate column k
  mutate(y=(z*100000)) %>% # calculate column l
  mutate(rthermistor=(y/(vbattery-z))) %>% # calculate Rthermistor
  mutate(durafet=(rthermistor*2)) # calculate durafet therm *THIS IS AN INTERMEDIATE VALUE UNTIL TRUE VALUE CAN BE CALCULATED*
```

### Calculating Durafet Therm
```{r}

```

### Calculating Tris pH
```{r}
temp <- c(omegas_v$durafet) # copy durafet therm into tris pH template
b <- as.numeric(rep("11911.08",length(temp))) # create vector for tris pH template column b
c <- as.numeric(rep("18.2499",length(temp))) # create vector for tris pH template column c
d <- as.numeric(rep("0.039336",length(temp))) # create vector for tris pH template column d
e <- as.numeric(rep("366.27059",length(temp))) # create vector for tris pH template column e
f <- as.numeric(rep("0.53993607",length(temp))) # create vector for tris pH template column f
g <- as.numeric(rep("0.00016329",length(temp))) # create vector for tris pH template column g
h <- as.numeric(rep("64.52243",length(temp))) # create vector for tris pH template column h
i <- as.numeric(rep("0.084041",length(temp))) # create vector for tris pH template column i
j <- as.numeric(rep("0.11149858",length(temp))) # create vector for tris pH template column j
m <- as.numeric(rep("35",length(temp))) # create vector for tris pH template column m
k <- as.numeric(rep("273.15",length(temp))) # create vector for tris pH template column k
tris_ph_template <- data.frame(temp,b,c,d,e,f,g,h,i,j,k,m)%>% # create tris pH template as a data frame with all above columns
  mutate(n=(b-(c*m)-(d*m*m))*1/k) %>% # create column n
  mutate(o=(-e+(f*m)+(g*m*m))) %>% # create column o
  mutate(p=(h-(i*m))*log(k)-(j*(k))) %>% # create column p
  mutate(trisph=(n+o+p)) # calculate tris pH, add as a new column to tris pH template data frame
```

### Calculating calibration values

## Create OMEGAS pH sheet
```{r}
omegas_calibration <- data.frame(omegas_v$durafet,omegas_v$v1) %>% # create data frame with durafet therm and voltage 1 values
  mutate(trisph=tris_ph_template$trisph) %>% # add tris pH values into calibration dataframe 
  mutate(tk=omegas_v$durafet+273.15) %>% # add TK column to data frame
  mutate(st=(8.31451*tk/96487*log(10))) %>% # add S(T) column to data frame
  mutate(eot=(-0.374911706-(0.001*(tk-290.2751473)))) %>% # add Eo(T) column to data frame
  mutate(omegasph=(omegas_v$v1-eot)/st) %>% # add pH column to data frame
  mutate(diff=(trisph-omegasph)) %>% # add difference column (tris pH - omegas pH) to data frame
  mutate(tempdiff=omegas_v.durafet-lag(omegas_v.durafet,n=5,default=first(omegas_v.durafet))) %>% # find difference between two temp measurements 5 rows apart to identify where temperature stabilizes
    mutate(phdiff=omegasph-lag(omegasph,n=5,default=first(omegasph))) # find difference between two pH measurements 5 rows apart to identify where pH stabilizes
```

## Choose calibration values
```{r}
omegas_cleaned <- omegas_calibration %>% # create new data frame after deleting first 150 rows
  filter(row_number()!=c(1:150)) %>% # remove the first 150 rows (first 30 minutes of data)
  filter(omegas_calibration,phdiff==min(phdiff)) %>% # select the row that contains the minimum value of change in pH over time and add it alone to a new data frame
  add_row(filter(omegas_calibration,tempdiff==min(tempdiff))) # select the row that contains the minimum value of change in temperature over time and add it alone to the omegas_cleaned dataframe
  # what do we do when the row with min tempdiff and the row with min phdiff are different?
```